spring:
  application:
    name: ssakssakmeal
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ssakssakmeal
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:node}
    password: ${DB_PASSWORD:1234}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
