spring:
  application:
    name: ssakssakmeal
  datasource:
    url: jdbc:postgresql://192.168.1.24:5432/ssakssakmeal
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  profiles:
    active: dev

